######################################################################
# Automatically generated by qmake (2.01a) Thu Feb 7 19:36:18 2008
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = ../bin/tests
DEPENDPATH += . 
INCLUDEPATH += . ../src /usr/include/hdf

LIBS += -L../bin/ -llidarconverter

# Input
HEADERS += testdatasource.h \
	   testhelper.h
SOURCES += testdatasource.cpp \
	   tests.cpp \
	   testhelper.cpp
